articles/urls.py
from django.urls import path, include

from . import views

# this appname is used inside the html templates   ...for example if we want to get the home url we type articles:home....if you want to get the detail page we type articles:detail
app_name = "articles"

urlpatterns = [
    path("", views.ArticleListView.as_view(), name="article_list"),

    path("article/<int:pk>", views.ArticleDetailView,
         name="article_detail"),

    path("search-results/", views.ArticleSearchView.as_view(), name="search_results"),

    path('article/create', views.ArticleCreateView.as_view(), name='add_article'),

    path('article/update/<int:pk>',
         views.ArticleUpdateView.as_view(), name='edit_article'),

    path('article/delete/<int:pk>',
         views.ArticleDeleteView.as_view(), name="delete_article"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('dashboard/', include('articles.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
    # path('articles/comments/', include('django_comments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url

from . import views

app_name = "users"
urlpatterns = [
    # url(regex=r"^$", view=views.UserListView.as_view(), name="list"),
    #url(regex=r"^~redirect/$", view=views.UserRedirectView.as_view(), name="redirect"),
    url(regex=r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),

    url(
        regex=r"^(?P<username>[\w.@+-]+)/$",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

articles/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.
class ArticleCategory(models.Model):
    article_category = models.CharField(max_length=200)
    article_summary = models.CharField(max_length=200)
    article_slug = models.CharField(max_length=200)

    class Meta:
        # this is for the admin
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.article_category


class ArticleSeries(models.Model):
    article_series = models.CharField(max_length=200)
    article_category = models.ForeignKey(
        ArticleCategory, default=1, verbose_name="Category", on_delete=models.SET_DEFAULT)
    series_summary = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "Series"

    def __str__(self):
        return self.article_series


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                             related_name="publisher", on_delete=models.SET_NULL)
    title = models.CharField(max_length=100)
    body = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    # categories = models.ManyToManyField(
    #     'ArticleSeries', related_name="article")

    tutorial_series = models.ForeignKey(
        ArticleSeries, default=1, verbose_name="Series", on_delete=models.SET_DEFAULT)
    tutorial_slug = models.CharField(max_length=200, default=1)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('articles:article_list')
    # if we want the absolute url to redirect to a detail page for examplel
    # def get_absolute_url(self):
    #    return reverse('detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    email = models.EmailField()
    created_on = models.DateTimeField(auto_now_add=True)

    comment_article = models.ForeignKey(
        'Article', null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name_plural = "Comments"

    def __str__(self):
        return self.author

articles/forms.py
from django import forms
from articles.models import Article, Comment
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", 'body']
        widgets = {
            'body': SummernoteWidget(),
            # 'body': SummernoteInplaceWidget()
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author', "email", "body"]


# class CommentForm(forms.Form):
#     author = forms.CharField(
#         max_length=60,
#         widget=forms.TextInput(attrs={
#             "class": "form-control",
#             "placeholder": "Your Name"
#         })
#     )

#     email = forms.CharField(
#         max_length=60,
#         widget=forms.TextInput(attrs={
#             "class": "form-control",
#             "placeholder": "Your Email"
#         })
#     )

#     body = forms.CharField(
#         widget=forms.Textarea(attrs={
#             "class": "form-control",
#             "placeholder": "Your Name"
#         })
#     )

articles/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render

from django.db.models import Q
from django.urls import reverse

from . models import Article, Comment
from .forms import ArticleForm, CommentForm

# article List View class


class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = "articles/article_list.html"
    paginate_by = 5
    ordering = "pub_date"

# article search list results view


class ArticleSearchView(LoginRequiredMixin, ListView):
    model = Article
    template_name = "articles/article_search_results.html"
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Article.objects.filter(
            Q(title__icontains=query) | Q(body__icontains=query)
        )
        return object_list

# article details view class


# class ArticleDetailView(LoginRequiredMixin, DetailView):
#     model = Article
#     template_name = "articles/article_detail.html"

def ArticleDetailView(request, pk):
    article = Article.objects.get(pk=pk)
    comments = Comment.objects.filter(
        comment_article=article).order_by('created_on')
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                email=form.cleaned_data["email"],
                body=form.cleaned_data["body"],
                comment_article=article
            )
            comment.save()

    context = {
        "article": article,
        "comments": comments,
        "form": form
    }
    return render(request, "articles/article_detail.html", context)

# article create view class


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    #fields= ["title", "body"]
    # defines how the html file name will look like
    template_name_suffix = '_create_form'
    # default is model_create_form.html
    # the suffix property defines what the generalshape for the template name is and by default it takes the model name and then we define in the suffix whats next
    # the template_name sets the name manually
    form_class = ArticleForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("articles:article_list")

# article update view class


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    #fields =["title", "body"]
    template_name_suffix = '_update_form'
    # default is model_update_form.html
    # the suffix property defines what the generalshape for the template name is and by default it takes the model name and then we define in the suffix whats next
    form_class = ArticleForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("articles:article_list")


# article delete view class
class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('articles:article_list')
    # this name home comes from the urls
    # default is author_confirm_delete.html

templates/articles/article_confirm_delete.html
{% extends 'base.html' %}
{% block title %} Delete ? {% endblock title %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

templates/articles/article_create_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create new {% endblock title %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Create Article</h1>

    <form action="{% url 'articles:add_article' %}" enctype="multipart/form-data" id="article-form" method="POST"
      role="form">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="form-group">
        <button type="submit" class="btn btn-primary publish"> Publish </button>

        <a href="{% url 'articles:article_list' %}" class="btn btn-default"> Cancel </a>
      </div>
    </form>
    {{ form.media }}



  </div>
</div>
{% endblock content %}

templates/articles/article_detail.html
{% extends 'base.html' %}

<!-- {% block title %} {{ article.title }} {% endblock title %} -->
{% block content %}
<!-- Page Content -->
<div class="container">
	<div class="row">
		<!-- Post Content Column -->
		<div class="col-lg-8">
			<!-- Title -->
			<h1 class="mt-4">{{ article.title }}</h1>
			<!-- Author -->
			<p class="lead">by
				<a href="{% url 'users:detail' article.user.username %}">{{ article.user.get_profile_name|title }}</a>
			</p>
			<hr>
			<!-- Date/Time -->
			<p>Posted {{ article.pub_date }} </p>
			<hr>
			<!-- Post Content -->
			<p class="card-text">{{ article.body|safe }}</p>
			<hr>
			<p>Series : {{ article.tutorial_series }}</p>
		</div><!-- end col-lg-->


		<div class="col-md-4">

			<!-- Write Article Widget -->
			{% if request.user.is_authenticated %}
			<div class="card my-4">
				<div class="card-body text-center">
					<a class="btn btn-success" href="{% url 'articles:add_article' %}" title="Write a new article"><i
							class="fa fa-pencil" aria-hidden="true"></i> New Article</a>

					<a class="btn btn-primary" href="{% url 'articles:edit_article' article.pk %}"
						title="Edit this article"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a>

					<a class="btn btn-danger" href="{% url 'articles:delete_article' article.pk %}"
						title="Delete this article"><i class="fas fa-trash-alt" aria-hidden="true"></i> Delete </a>


				</div>
			</div>
			{% endif %}

		</div>

	</div>
	<!--end row-->
	<div class="row">
		<div class="col-12">
			<h2>Leave a reply</h2>
			<form action="/dashboard/article/{{article.pk}}" method="POST">
				{% csrf_token %}
				{{form.as_ul}}
				<!-- <div class="from-group">
					{{from.author}}
				</div>
				<div class="from-group">
					{{from.email}}
				</div>
				<div class="from-group">
					{{from.body}}
				</div> -->
				<button class="btn btn-info" type="submit">Submit</button>
			</form>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<h2>Comments:</h2>
			{% if comments %}
			<ul>
				{% for comment in comments %}
				<li>
					<h6>Author : {{ comment.author }}</h6>
					<p><i>{{comment.created_on}}</i></p>
					<div>
						<p>{{comment.body}}</p>
					</div>
				</li>
				{% endfor %}
			</ul>
			{% else %}
			<p>No comments yet be the first to add one above</p>
			{% endif %}
		</div>
	</div>
</div>
<!-- end container-->
{% endblock content %}

templates/articles/article_list.html
{% extends 'base.html' %}
{% block title %} Dashboard {% endblock title %}
{% block content %}
<!-- Page Content -->
<div class="container">
	<div class="row my-3">
		<!-- Blog Entries Column -->
		<div class="col-md-8 ">
			{% for article in object_list %}
			<!-- Blog Post -->
			<div class="card p-0 mb-4">
				<!-- body -->
				<div class="card-body p-4">
					<h2 class="card-title">{{ article.title }}</h2>
					<p class="card-text">{{ article.body|truncatechars:150 }}</p>
					<a href="{% url 'articles:article_detail' article.pk %}" style="color:#f4f4f4"
						class="btn btn-primary">Read More
						&rarr;</a>
				</div>
				<!-- footer -->
				<div class="card-footer text-muted">
					Posted : {{ article.pub_date }}
				</div>
			</div>
			<!--end card-->
			{% empty %}
			<h4 class="no-data">There is no published article yet . <a href="{% url 'articles:add_article' %}">Be the
					first one to publish one </a></h4> {% endfor %}
			<!-- pagination-->
			{% if is_paginated %}
			<ul class="pagination justify-content-center mb-4">
				{% if page_obj.has_previous %}
				<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr;
						Newer</a></li>
				{% else %}
				<li class="page-item disabled"><a class="page-link" href="#"><span>&larr;</span></a></li>
				{% endif %}

				{% for i in paginator.page_range %}
				{% if page_obj.number == i %}
				<li class="page-item disabled"><a class="page-link" href="#">{{ i }} <span
							class="sr-only">(current)</span></a></li>
				{% else %}
				<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
				{% endif %}
				{% endfor %}

				{% if page_obj.has_next %}
				<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Older'
						&rarr;</a></li>
				{% else %}
				<li class="page-item disabled"><a class="page-link" href="#"><span>&rarr;</span></a></li>
				{% endif %}

			</ul>
			{% endif %}
			<!-- end pagination-->
		</div>
		<!-- Sidebar Widgets Column -->
		<div class="col-md-4">
			<!-- Write Article Widget -->
			{% if request.user.is_authenticated %}
			<div class="card my-4">
				<div class="card-body text-center">
					<div class="my-3">
						<a class="btn btn-success" href="{% url 'articles:add_article' %}" title="Write a new article">
							<i class="fa fa-pencil" aria-hidden="true"></i> New Article
						</a>
					</div>
					<form action="{% url 'articles:search_results' %}" method="get">
						<input class="d-block mx-auto" name="q" type="text" placeholder="Search..." required>
						<button class="btn btn-success my-1" type="submit" title="submit">
							<i class="fa fa-search" aria-hidden="true"></i> Search
						</button>
					</form>
				</div>
			</div>
			{% endif %}
		</div>
	</div>
</div>

{% endblock content %}

templates/articles/article_search_results.html
{% extends "base.html" %}
{% block title %} Search Results {% endblock title %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <h1>Search Results</h1>
    </div>
    <div class="row my-3">

        <!-- Blog Entries Column -->
        <div class="col-md-8 ">
            {% for article in object_list %}
            <!-- Blog Post -->
            <div class="card p-0 mb-4">
                <!-- body -->
                <div class="card-body p-4">
                    <h2 class="card-title">{{ article.title }}</h2>
                    <p class="card-text">{{ article.body|truncatechars:150 }}</p>
                    <a href="{% url 'articles:article_detail' article.pk %}" class="btn btn-primary"
                        style="color:#f4f4f4">Read More &rarr;
                    </a>
                </div>
                <!-- footer -->
                <div class="card-footer text-muted">
                    Posted : {{ article.pub_date }}
                </div>
            </div>
            <!--end card-->
            {% empty %}
            <h4 class="no-data">There is no Results for your search . </h4>
            {% endfor %}

        </div>
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">
            <!-- Write Article Widget -->
            {% if request.user.is_authenticated %}
            <div class="card my-4">
                <div class="card-body text-center">
                    <form action="{% url 'articles:search_results' %}" method="get">
                        <input class="d-block mx-auto" name="q" type="text" placeholder="Search..." required>
                        <button class="btn btn-success my-1" type="submit" title="submit">
                            <i class="fa fa-search" aria-hidden="true"></i> Search
                        </button>
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/articles/article_update_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Edit Article {% endblock title %}
{% block content%}
<div class="container">
  <div class="jumbotron">
    <h1>Edit Article</h1>

    <form action="{% url 'articles:edit_article' form.instance.pk %}" enctype="multipart/form-data" id="article-form"
      method="POST" role="form">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="form-group">
        <button type="submit" class="btn btn-primary update">Update</button>
        <a href="{% url 'articles:article_list' %}" class="btn btn-default"> Cancel </a>
      </div>
    </form>
    {{ form.media }}


  </div>
</div>
{% endblock %}