articles/urls.py
from django.urls import path, include

from . import views

# this appname is used inside the html templates   ...for example if we want to get the home url we type articles:home....if you want to get the detail page we type articles:detail
app_name = "articles"

urlpatterns = [
    path("", views.ArticleListView.as_view(), name="article_list"),

    path("article/<int:pk>", views.ArticleDetailView,
         name="article_detail"),

    path("search-results/", views.ArticleSearchView.as_view(), name="search_results"),

    path('article/create', views.ArticleCreateView.as_view(), name='add_article'),

    path('article/update/<int:pk>',
         views.ArticleUpdateView.as_view(), name='edit_article'),

    path('article/delete/<int:pk>',
         views.ArticleDeleteView.as_view(), name="delete_article"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('dashboard/', include('articles.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
    # path('articles/comments/', include('django_comments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url

from . import views

app_name = "users"
urlpatterns = [
    # url(regex=r"^$", view=views.UserListView.as_view(), name="list"),
    #url(regex=r"^~redirect/$", view=views.UserRedirectView.as_view(), name="redirect"),
    url(regex=r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),

    url(
        regex=r"^(?P<username>[\w.@+-]+)/$",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
		integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/landing.css' %}">
	{% block css %}

	{% endblock css %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
	<title>{% block title %}{% endblock %}</title>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-white">
		<div class="container">
			<a class="navbar-brand" href="/">Conforms.online</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="/about">About</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/admin">Admin</a>
					</li>

				</ul>
				{% if user.is_authenticated %}
				<ul class="navbar-nav my-lg-0">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:detail' request.user.username  %}">Profile</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'articles:article_list' %}">dashboard</a>
					</li>
					<a href="/accounts/logout/" class="btn btn-success">Logout</a>
				</ul>
				{% else %}
				<ul class="navbar-nav my-lg-0">
					<a href="/accounts/login/" class="btn btn-success">Get Started</a>
				</ul>
				{% endif %}
			</div>
		</div>
	</nav>

	{% block content %}

	{% endblock content %}

	<!-- Site footer -->
	<footer class="site-footer" id="about">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-md-6">
					<h6>About</h6>
					<p class="text-justify">confroms.online Lorem ipsum dolor sit amet, consectetur adipisicing
						elit. Sed sunt non obcaecati, vero ipsam, aut, fugit consectetur asperiores rem culpa
						placeat quo, enim odit. At reiciendis consectetur totam deleniti laudantium sit, natus quia
						qui! Ipsum quis quos quidem aliquid, illum.</p>
				</div>

				<div class="col-xs-6 col-md-3">
				</div>

				<div class="col-xs-6 col-md-3">
					<h6>Quick Links</h6>
					<ul class="footer-links">
						<li><a href="http://scanfcode.com/about/">About Us</a></li>
						<li><a href="http://scanfcode.com/contact/">Contact Us</a></li>
						<li><a href="http://scanfcode.com/contribute-at-scanfcode/">Contribute</a></li>
						<li><a href="http://scanfcode.com/privacy-policy/">Privacy Policy</a></li>
						<li><a href="http://scanfcode.com/sitemap/">Sitemap</a></li>
					</ul>
				</div>
			</div>
			<hr>
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-sm-6 col-xs-12">
						<p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by
							<a href="#">manascode.com</a>.
						</p>
					</div>

					<div class="col-md-4 col-sm-6 col-xs-12">
						<ul class="social-icons">
							<li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
							<li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- end -->

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
		integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
		integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
		integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
		crossorigin="anonymous"></script>
	</div>
</body>

</html>