blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('dashboard/', include('articles.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
    # path('articles/comments/', include('django_comments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url

from . import views

app_name = "users"
urlpatterns = [
    # url(regex=r"^$", view=views.UserListView.as_view(), name="list"),
    #url(regex=r"^~redirect/$", view=views.UserRedirectView.as_view(), name="redirect"),
    url(regex=r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),

    url(
        regex=r"^(?P<username>[\w.@+-]+)/$",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):
    # First Name and Last Name do not cover name patterns around the globe.
    name = models.CharField(blank=True, max_length=255)

    picture = models.ImageField(
        upload_to="profile_pics/", null=True, blank=True)

    location = models.CharField(max_length=50, null=True, blank=True)

    job_title = models.CharField(max_length=50, null=True, blank=True)

    personal_url = models.URLField(max_length=555, blank=True, null=True)

    facebook_account = models.URLField(max_length=255, blank=True, null=True)

    twitter_account = models.URLField(max_length=255, blank=True, null=True)

    github_account = models.URLField(
        max_length=255, blank=True, null=True)

    linkedin_account = models.URLField(
        max_length=255, blank=True, null=True)

    short_bio = models.CharField(max_length=60, blank=True, null=True)

    bio = models.CharField(max_length=280, blank=True, null=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    def get_profile_name(self):
        if self.name:
            return self.name

        return self.username

users/views.py
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

# class UserRedirectView(LoginRequiredMixin, RedirectView):
#    permanent = False

#    def get_redirect_url(self):
#        return reverse("users:detail", #kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = [
        "name",
        "email",
        "picture",
        "job_title",
        "location",
        "personal_url",
        "facebook_account",
        "twitter_account",
        "github_account",
        "linkedin_account",
        "short_bio",
        "bio",
    ]
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(ListView):
    model = User
    # These next two lines tell the view to index lookups by username

templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link href="{% static 'general/css/user_profile.css' %}" rel="stylesheet">
{% endblock css %}

{% block title %}{{ object.username }}{% endblock %}

{% block content %}
<div class="container">
  <div class="row my-4">
    <!-- details part -->
    <div class="col-md-9">
      <div id="contact-info" class="vcard">
        <h1 class="fn">
          {{ object.username|title }}
          {% if object.short_bio %}
          <br /><small style="font-size: 50%">{{ object.short_bio }}</small>
          {% endif %}
        </h1>
        <p>
          <i class="fa fa-user-circle-o" aria-hidden="true"></i>
          {{ object.get_profile_name|title }}
          <br />
          <i class="fa fa-envelope" aria-hidden="true"></i><a class="email" href="mailto:{{ object.email }}">
            {{ object.email }}</a><br />
          {% if object.job_title %}
          <i class="fa fa-briefcase" aria-hidden="true"></i> {{ object.job_title }} <br />
          {% endif %}
          {% if object.location %}
          <i class="fa fa-map-marker" aria-hidden="true"></i> {{ object.location }} <br />
          {% endif %}
        </p>
      </div>
      <div id="objective">
        <p>{{ object.bio }}</p>
      </div>
      {% if object.personal_url %}
      <a href="{{ object.personal_url }}" style="font-size: 2em" title="RSS Channel"><i class="fa fa-rss"></i>
      </a>
      {% endif %}
      {% if object.twitter_account %}
      <a href="{{ object.twitter_account }}" style="font-size: 2em" title="Twitter Profile"><i
          class="fa fa-twitter"></i>
      </a>
      {% endif %}
      {% if object.github_account %}
      <a href="{{ object.github_account }}" style="font-size: 2em" title="Github Profile"><i class="fa fa-github"></i>
      </a>
      {% endif %}
      {% if object.linkedin_account %}
      <a href="{{ object.linkedin_account }}" style="font-size: 2em" title="LinkedIn Profile"><i
          class="fa fa-linkedin"></i> </a>
      {% endif %}
      {% if object.facebook_account %}
      <a href="{{ object.facebook_account }}" style="font-size: 2em" title="Facebook Profile"><i
          class="fa fa-facebook"></i> </a>
      {% endif %}
    </div>
    <!-- image part  -->
    <div class="col-md-3 ">
      {% if object.picture %}
      <img src="/media/{{ user.picture }}" alt="Picture Profile" style="width:100%" id="pic">
      {% else %}
      <img class="pull-right" src="{% static 'general/img/user.png' %}" style="width:100%" height="250px"
        alt="No Profile Picture" />
      {% endif %}
    </div>



  </div>
  {% if request.user.username == object.username %}
  <!-- Data tiles -->
  <div class="row tile_count">
    <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
      <span class="count_top"><i class="glyphicon glyphicon-envelope"></i> Feeds </span>
      <div class="count">0</div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
      <span class="count_top"><i class="glyphicon glyphicon-pencil"></i> Articles</span>
      <div class="count">0</div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
      <span class="count_top"><i class="glyphicon glyphicon-comment"></i> Comments</span>
      <div class="count">0</div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
      <span class="count_top"><i class="glyphicon glyphicon-question-sign"></i> Questions</span>
      <div class="count">0</div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
      <span class="count_top"><i class="glyphicon glyphicon-education"></i> Answers</span>
      <div class="count">0</div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
      <span class="count_top"><i class="glyphicon glyphicon-fire"></i> Global Interactions</span>
      <div class="count">0</div>
    </div>
  </div>
  <div class="row my-3">
    <a class="btn btn-dark pull-right d-block" href="{% url 'users:update' %}">Update Profile</a>
  </div>
</div>

<!-- /data tiles -->
{% endif %}
{% endblock content %}

templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block css %}
<link href="{% static 'general/css/user_form.css' %}?v=1" rel="stylesheet">
{% endblock css %}

{% block title %} Edit {{ object.username }} Info {% endblock title %}

{% block content %}
<div class="container">
  <div class="row profile">
    <div class="col-md-4 user-profile">
      <h1>{{ user.username|title }}</h1>

      {% if user.name %}<p class="lead">{{ user.name }}</p>{% endif %}

      <div>
        {% if user.picture %}
        <img src="/media/{{ user.picture }}" style="width:100%" alt="Picture Profile" id="pic">
        {% else %}
        <img src="{% static 'general/img/user.png' %}" style="width:100%" alt="No Profile Picture" />
        {% endif %}
      </div>
    </div>

    <div class="col-md-8">
      <form enctype="multipart/form-data" class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn btn-dark">Update Profile</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/users/user_list.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link href="{% static 'general/css/user_list.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}

<div class="page-header">
  <h1>Contacts</h1>
</div>

<ul class="user-profiles-list">
  {% for user in user_list %}
  <li>
    <div class="user-avatar">
      <a href="{% url 'users:detail' user.username  %}" class="user-avatar">

        {% if user.picture %}
        <img src="/media/{{ user.picture }}" alt="Picture Profile" id="pic">
        {% else %}
        <img src="{% static 'img/user.png' %}" alt="No Profile Picture" />
        {% endif %}

      </a>
    </div>
    <p>
      <i class="fa fa-envelope" aria-hidden="true"></i>
      <a class="email" href="mailto:{{ user.email }}">
        {{ user.get_profile_name|title }}
      </a>
      <span>
        {% if user.job_title %}
        <i class="fa fa-briefcase" aria-hidden="true"></i>
        <i> {{ user.job_title}}</i>
        {% endif %}
      </span>
      <span>
        {% if user.location %}
        <i class="fa fa-map-marker" aria-hidden="true"></i>
        <i> {{ user.location }}</i>
        {% endif %}
      </span>
    </p>
  </li>
  {% endfor %}
</ul>

{% endblock content %}